package me.shovon.sms2wallet.data.sms

import android.util.Log
import java.security.MessageDigest
import java.util.Locale
import me.shovon.bdparser.ParsedTransaction
import me.shovon.sms2wallet.data.local.dao.AccountMappingDao
import me.shovon.sms2wallet.data.local.dao.CategoryRuleDao
import me.shovon.sms2wallet.data.local.dao.TransactionDao
import me.shovon.sms2wallet.data.local.dao.UnmatchedSmsDao
import me.shovon.sms2wallet.data.local.entity.AccountMappingEntity
import me.shovon.sms2wallet.data.local.entity.TransactionEntity
import me.shovon.sms2wallet.data.local.entity.UnmatchedSmsEntity
import me.shovon.sms2wallet.data.local.entity.WalletCategoryEntity
import me.shovon.sms2wallet.domain.category.MerchantCategoryGuesser
import me.shovon.sms2wallet.domain.model.PushState

private const val TAG = "RoomIngestSink"

/** +/- window, centred on the transaction's own timestamp, searched for a cross-provider duplicate. */
private const val DUPLICATE_WINDOW_MILLIS = 10 * 60 * 1000L

/**
 * Room's autogenerated row ids start at 1, so this sentinel can never collide with a real row -
 * it is passed to [TransactionDao.findPotentialDuplicate] when checking for a cross-provider
 * duplicate *before* the candidate row itself has been inserted (and therefore has no real id
 * yet to exclude).
 */
private const val NO_EXISTING_ROW_ID = 0L

/**
 * Persistence-backed [IngestSink]: turns a parsed/unmatched/ignored SMS outcome into rows in
 * the local database.
 *
 * [autoPushBankNames] mirrors the lazy-token-provider pattern used by
 * `KtorWalletApiClient.tokenProvider` - it is read fresh on every [accept] call (typically
 * backed by `AppPreferences.autoPushParserNames`) rather than snapshotted once, since the user
 * can change which banks auto-push at any time from settings.
 *
 * [debugLog] follows the same seam as `RedactingLogger.sink`: a plain `(String) -> Unit`
 * defaulting to [android.util.Log.d] in production, so plain JVM unit tests (which run without
 * Robolectric and therefore have no working `android.util.Log`) can inject a no-op instead of
 * crashing on the unmocked Android stub. Never pass SMS content to it - only fixed,
 * PII-free diagnostic strings.
 */
class RoomIngestSink(
    private val transactionDao: TransactionDao,
    private val accountMappingDao: AccountMappingDao,
    private val categoryRuleDao: CategoryRuleDao,
    private val unmatchedSmsDao: UnmatchedSmsDao,
    private val autoPushBankNames: suspend () -> Set<String>,
    /** The user's synced Wallet categories, read lazily so a fresh sync is picked up. */
    private val walletCategories: suspend () -> List<WalletCategoryEntity>,
    /**
     * Invoked after a row is stored in [PushState.QUEUED], to kick off the send.
     *
     * A callback rather than a direct `PushScheduler` dependency so this class stays a plain
     * unit-testable object with no Android/WorkManager types in its constructor.
     */
    private val onQueued: () -> Unit = {},
    /**
     * Called once a transaction has been stored: (id, merchant, amount, type, needsReview).
     *
     * A callback rather than a `TransactionNotifier` dependency so this class stays a plain
     * unit-testable object with no Android types in its constructor.
     */
    private val onIngested: (Long, String?, java.math.BigDecimal, String, Boolean) -> Unit =
        { _, _, _, _, _ -> },
    private val debugLog: (String) -> Unit = { message -> Log.d(TAG, message) },
) : IngestSink {

    override suspend fun accept(result: IngestResult, raw: RawSms) {
        when (result) {
            is IngestResult.Parsed -> acceptParsed(result.transaction)
            is IngestResult.Unmatched -> acceptUnmatched(result, raw)
            is IngestResult.Ignored -> Unit // Nothing to persist.
        }
    }

    private suspend fun acceptParsed(parsedTransaction: ParsedTransaction) {
        val mapping = resolveMapping(parsedTransaction)

        val pushState = resolveInitialPushState(parsedTransaction, mapping)
        val duplicateOfId = mapping?.walletAccountId?.let { walletAccountId ->
            findSuspectedDuplicateId(walletAccountId, parsedTransaction)
        }

        // A suspected duplicate always needs a human's eyes on it, no matter how the auto-push
        // rule above resolved: never auto-discard it (it is still stored) and never auto-push it.
        val resolvedPushState = if (duplicateOfId != null) PushState.PARSED else pushState

        val categoryId = resolveCategoryId(parsedTransaction, mapping)
        val now = System.currentTimeMillis()

        val entity = TransactionEntity(
            transactionHash = parsedTransaction.transactionHash ?: parsedTransaction.generateTransactionId(),
            bankName = parsedTransaction.bankName,
            accountLast4 = parsedTransaction.accountLast4,
            amount = parsedTransaction.amount.toPlainString(),
            type = parsedTransaction.type.name,
            merchant = parsedTransaction.merchant,
            reference = parsedTransaction.reference,
            currency = parsedTransaction.currency,
            smsSender = parsedTransaction.sender,
            smsBody = parsedTransaction.smsBody,
            timestamp = parsedTransaction.timestamp,
            pushState = resolvedPushState.name,
            walletRecordId = null,
            walletAccountId = mapping?.walletAccountId,
            walletCategoryId = categoryId,
            lastError = null,
            attemptCount = 0,
            suspectedDuplicateOfId = duplicateOfId,
            createdAt = now,
            updatedAt = now,
        )

        // insertIgnore relies on the unique index on transaction_hash: a -1 return means an SMS
        // that generates the same hash (i.e. the exact same message) was already ingested, most
        // likely by a rescan. That is expected and NOT an error - log at debug and stop, without
        // performing any of the side effects (queueing, duplicate flags, etc.) a second time.
        val insertedId = transactionDao.insertIgnore(entity)
        if (insertedId == -1L) {
            debugLog("Ignoring already-ingested SMS (transaction_hash already present)")
            return
        }

        val autoPushed = resolvedPushState == PushState.QUEUED
        if (autoPushed) {
            // An auto-pushed row is only queued here; this is what actually starts the send.
            onQueued()
        }

        // Tell the user either way: silently filing a transaction they never saw is exactly the
        // behaviour that makes people distrust an app that touches their money.
        onIngested(
            insertedId,
            parsedTransaction.merchant,
            parsedTransaction.amount,
            parsedTransaction.type.name,
            !autoPushed,
        )
    }

    /**
     * The mapping to route this transaction with: the exact (bank, last-4) pair if one exists,
     * otherwise any mapping for the bank.
     *
     * Without the fallback, mapping a provider only covered messages whose last-4 happened to
     * match the one present when the mapping was made, so most transactions still arrived with
     * no account attached.
     */
    private suspend fun resolveMapping(parsedTransaction: ParsedTransaction): AccountMappingEntity? =
        accountMappingDao.findByBankAndLast4(
            bankName = parsedTransaction.bankName,
            accountLast4 = parsedTransaction.accountLast4 ?: AccountMappingEntity.UNKNOWN_LAST4,
        ) ?: accountMappingDao.findAnyByBank(parsedTransaction.bankName)

    /**
     * A source (bank + last-4, see [AccountMappingEntity.UNKNOWN_LAST4]) with no
     * [AccountMappingEntity] is not routed to any Wallet account, so it can **never** be
     * [PushState.QUEUED] - there is nothing to push it to - regardless of whether auto-push is
     * enabled for that bank. Only a mapped source whose bank is also in [autoPushBankNames] is
     * queued; every other case lands in [PushState.PARSED] for manual review.
     */
    private suspend fun resolveInitialPushState(
        parsedTransaction: ParsedTransaction,
        mapping: AccountMappingEntity?,
    ): PushState {
        if (mapping == null) return PushState.PARSED
        val autoPushBanks = autoPushBankNames()
        return if (parsedTransaction.bankName in autoPushBanks) PushState.QUEUED else PushState.PARSED
    }

    /**
     * Cross-provider ("L2") duplicate check: looks for another locally-known transaction against
     * the same Wallet account, with the same amount, within [DUPLICATE_WINDOW_MILLIS] of this
     * one's own timestamp. Catches the case where the same real-world payment is reported by more
     * than one SMS source, which the transaction_hash-based ("L1") dedup in [acceptParsed] cannot
     * catch since the two SMS bodies differ.
     *
     * Runs *before* this transaction's own row exists, so [NO_EXISTING_ROW_ID] is passed as the
     * id to exclude - a sentinel that can never match any real (autogenerated, 1-based) row.
     */
    private suspend fun findSuspectedDuplicateId(
        walletAccountId: String,
        parsedTransaction: ParsedTransaction,
    ): Long? {
        val candidates = transactionDao.findPotentialDuplicate(
            walletAccountId = walletAccountId,
            amount = parsedTransaction.amount.toPlainString(),
            fromTs = parsedTransaction.timestamp - DUPLICATE_WINDOW_MILLIS,
            toTs = parsedTransaction.timestamp + DUPLICATE_WINDOW_MILLIS,
            excludeId = NO_EXISTING_ROW_ID,
        )
        return candidates.firstOrNull()?.id
    }

    /**
     * Highest-priority [me.shovon.sms2wallet.data.local.entity.CategoryRuleEntity] whose keyword
     * case-insensitively matches the transaction's merchant, falling back to the account
     * mapping's [AccountMappingEntity.defaultCategoryId], then `null`.
     */
    private suspend fun resolveCategoryId(
        parsedTransaction: ParsedTransaction,
        mapping: AccountMappingEntity?,
    ): String? {
        val merchant = parsedTransaction.merchant
        if (!merchant.isNullOrBlank()) {
            // User-defined rules win: they are an explicit decision about this merchant.
            val rules = categoryRuleDao.findApplicableRules(parsedTransaction.bankName)
            val matched = rules.firstOrNull { rule ->
                merchant.contains(rule.keyword, ignoreCase = true)
            }
            if (matched != null) return matched.walletCategoryId

            // Then the built-in merchant map, resolved against the user's own categories.
            val guessed = MerchantCategoryGuesser.guess(merchant, walletCategories())
            if (guessed != null) return guessed
        }
        return mapping?.defaultCategoryId
    }

    private suspend fun acceptUnmatched(result: IngestResult.Unmatched, raw: RawSms) {
        unmatchedSmsDao.insertIgnore(
            UnmatchedSmsEntity(
                smsHash = hashSms(raw),
                sender = raw.sender,
                body = raw.body,
                timestamp = raw.timestamp,
                reason = result.reason,
            )
        )
    }

    /** Stable hash of sender+body, matching [UnmatchedSmsEntity.smsHash]'s contract. */
    private fun hashSms(raw: RawSms): String {
        val data = "${raw.sender.trim()}|${raw.body.trim()}"
        return MessageDigest.getInstance("SHA-256")
            .digest(data.toByteArray())
            .joinToString("") { String.format(Locale.ROOT, "%02x", it) }
    }
}
